### ISSUE TITLE
Problems installing on Kubuntu 18.04 with .asdf version manager version of nodejs -- "Cannot find module '/package.json'"

### ISSUE THREAD

**Issue by HuShifang** [purescript-contrib/node-purescript#60]
Attempting to install on a Kubuntu 18.04 system that uses `.asdf` as a version manager for nodejs (attempted with both v10.1.0 and 10.4.0) with `npm@6.1.0`; I have both `pulp@12.3.0` and `bower@1.8.4` already installed, along with Haskell Stack v1.7.1 (which is not installed via `.asdf`); the precompiled Purescript binary is saved at the path `~/Downloads/linux64.tar.gz` (not sure if local availability is relevant). 

When I run $ npm install -g purescript things seemingly go well at first but it inevitably errors out with the below log message. Asked around on Reddit, no one else seems to be having issue -- very possible that it's `.asdf` getting in the way or some other quirk of my system...

```
> purescript@0.12.0 postinstall ~/.asdf/installs/nodejs/10.1.0/.npm/lib/node_modules/purescript
> install-purescript --purs-ver=0.12.0 .

✖ Check if a prebuilt 0.12.0 binary is provided for Linux
  Error: Cannot find module '/package.json'
    at createModuleNotFoundRejection 
(~/.asdf/installs/nodejs/10.1.0/.npm/lib/node_modules/purescript/node_modules/load-from-cwd-or-npm/inde
x.js:34:22)
    at npmCliDir.then.npmCliDirPath 
(~/.asdf/installs/nodejs/10.1.0/.npm/lib/node_modules/purescript/node_modules/load-from-cwd-or-npm/inde
x.js:94:45)
▬ Download the prebuilt PureScript binary
▬ Verify the prebuilt binary works correctly
▬ Save the downloaded binary to the cache directory

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! purescript@0.12.0 postinstall: `install-purescript --purs-ver=0.12.0 .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the purescript@0.12.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-06-20T19_29_06_974Z-debug.log
```

**Comment by shinnn** [comment]
Fixed in https://github.com/shinnn/npm-cli-path/commit/dd923dd482e90593e8ad42dc3d58f13350114017. Retry `npm install -g purescript`.
