### ISSUE TITLE
can't install purescript

### ISSUE THREAD

**Issue by sagax** [purescript-contrib/node-purescript#65]
command
```
npm install -g purescript
```

simple log https://termbin.com/yene
complete log https://termbin.com/kzs7

- linux kernel 4.15.13-1-default
- node v8.12.0
- npm 6.4.1

**Comment by shinnn** [comment]
https://github.com/purescript/purescript/issues/3544#issuecomment-467960791 is a wrong direction. You ran into two problems neither of which is not directly related to this repository.

1. The prebuilt binary downloaded from https://github.com/purescript/purescript/releases/tag/v0.12.3 is not working.
2. `stack setup` command fails when using [PureScript's stack.yaml](https://github.com/purescript/purescript/blob/v0.12.3/stack.yaml). 

Use more appropriate issue trackers; https://github.com/purescript/purescript/issues for 1. and 2, https://github.com/commercialhaskell/stack/issues for 2.

**Comment by shinnn** [comment]
One of the PureScript maintainers explained the reason; currently uploaded binaries don't support 32-bit OSes. https://github.com/purescript/purescript/issues/3544#issuecomment-468225722
