### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by hdgarrood** [purescript-contrib/node-purescript#70]
Hi @shinnn,

The purescript npm package is a fantastic piece of work, and it's been really great for helping people to get the compiler installed successfully. We (the PureScript compiler maintainers) are very grateful for all of your work in creating and maintaining it.

However, we are beginning to feel that the current model is not working fantastically well. Specifically, we feel that our thoughts and interests do not always align with yours, and collaboration has not always been successful between us; conversations in issue trackers have often become unpleasant, for instance.

The fact that you are currently the only person who has the ability to publish releases to npm is also slightly problematic. In order for us to get releases published swiftly and without too much ceremony, it's important to us that each of us is able to publish. (As I recall, at one point Gary was also permitted to publish to npm, but you seem to have removed him.)

We would like to ask if you would be happy to donate the project and the npm package name to us for maintenance going forward. Of course you would retain copyright of the package, and we would comply with the license terms. We would move the project to the purescript organization, and the npm maintainers would be the purescript core team: me, @garyb, @joneshf, @kRITZCREEK, @LiamGoodacre, and @natefaubion.

Please let us know if this would be acceptable to you.

**Comment by shinnn** [comment]
I'd like to ask the rest of PureScript maintainers whether this is actually not just a personal opinion but the consensus of all of you.

Even though this request includes "we" and "us" repeatedly, it was originally sent to me via a personal e-mail by @hdgarrood, without Cc-ing any other maintainers. I suggested him to post it to this public issue tracker, anyway.

**Comment by shinnn** [comment]
> Please let us know if this would be acceptable to you.

Basically unacceptable. As one of enthusiastic OSS maintainers in this world, I am responsible to avoid establishing a precedent for a project transfer this way — a maintainer purges another active maintainer who is even an original author just because the former cannot compel the latter.

> we feel that our thoughts and interests do not always align with yours, and collaboration has not always been successful between us

That's how humans to be.

> conversations in issue trackers have often become unpleasant, for instance.

For whom? Actually I've damaged by frequent blames that this project should not take but the upstream compiler project should. Or, if you are talking about some of your proposals rejected by me because of technically valid reasons, they'd be somewhat unpleasant for you, yes. But that's how human society works. One cannot always get what they want.

> The fact that you are currently the only person who has the ability to publish releases to npm is also slightly problematic

This is the only opinion that seems reasonable to me. Because [some broken versions were published](https://github.com/purescript-contrib/node-purescript/issues/9) in former times, I've limited the access to the npm package. Though, since this repository now has [a fail-safe](https://github.com/purescript-contrib/node-purescript/blob/03b0abf26304ce7a239b489c0b86f552deb89f6f/package.json#L19), it's OK to add the purescript core members to npm. In order to prevent insecure versions being created by attackers, please enable [two-factor authentication](https://docs.npmjs.com/about-two-factor-authentication) before joining the team.

> the npm maintainers would be the purescript core team: me, @garyb, @joneshf, @kRITZCREEK, @LiamGoodacre, and @natefaubion.

I can add them, again, but without removing me. I even thought you're joking when I first read this sentence.

**Comment by hdgarrood** [comment]
Allow me to be more specific about what I meant by "conversations in issue trackers have often become unpleasant". Too often, you respond rudely to any suggestion that there might be a bug or UX issue in this project, as if you take the suggestion as a personal attack. (You haven't been "damaged" by these suggestions, as you claim; all mature programmers know that the occasional bug or UX issue is a fact of life in software engineering.) You also lock issues prematurely. For example:

- https://github.com/purescript/purescript/issues/3544
- https://github.com/purescript-contrib/node-purescript/issues/65
- https://github.com/purescript-contrib/node-purescript/issues/44
- https://github.com/purescript-contrib/node-purescript/issues/32

I especially don't want purescript newcomers to be exposed to this. So I no longer feel that trying to collaborate with you is workable.

The technical direction of the project is also an issue for me, although somewhat less pressing. I don't think we should drop support for older versions of Node as quickly as you do, for instance, but you've made your position on that very clear (#44). Your having this package print passive-aggressive messages to try to compel us into working on making the binary smaller (see https://github.com/shinnn/install-purescript-cli/issues/2, #68) is also not good, but to me it's more an illustration of how collaboration between us is not working than an issue of technical disagreement (although of course it is that too).

If you don't want to transfer the whole project (including the repository) to us, of course that's fine too; as you point out, it is your project. However I would like you to transfer the npm package name `purescript` to us. People will reasonably expect the `purescript` package to be maintained by the same people who maintain the compiler, the website purescript.org, and so on.

**Comment by kRITZCREEK** [comment]
> I'd like to ask the rest of PureScript maintainers whether this is actually not just a personal opinion but the consensus of all of you.

I fully agree with everything @hdgarrood has said here.

**Comment by joneshf** [comment]
> I'd like to ask the rest of PureScript maintainers whether this is actually not just a personal opinion but the consensus of all of you.

Thank you for checking. I support the opening comment.

> > conversations in issue trackers have often become unpleasant, for instance.
> 
> For whom?

The interaction in https://github.com/shinnn/install-purescript-cli/issues/1 was very unpleasant for me.

> (You haven't been "damaged" by these suggestions, as you claim; all mature programmers know that the occasional bug or UX issue is a fact of life in software engineering.)

I don't agree with this. In the same way our interactions with @shinnn have been painful (and there's nothing @shinnn can say that negates how we feel), @shinnn could feel that they have been damaged by their interactions with us.

**Comment by natefaubion** [comment]
I agree with the opening comment as well.

**Comment by garyb** [comment]
I'm in agreement too.

**Comment by shinnn** [comment]
I'm surprised that you use totally different criterion when you judge my attitude and yourselves'.

I said,

> I am responsible to avoid establishing a precedent for a project transfer this way — a maintainer (or maintainers) purges another active maintainer who is even an original author just because the former cannot compel the latter.

but now I have a strong reason to part with the `purescript` package; I feel ashamed to own `purescript`, whose developers allow this kind of unfairness.

I added `hdgarrood` to the npm package as an owner. Do what you want to.

**Comment by shinnn** [comment]
I'll delete this repository in the future. As far as I read https://github.com/shinnn/node-purescript/issues/70#issuecomment-499043752, you'd better recreate this project from scratch.

**Comment by garyb** [comment]
Sorry to hear that. Thanks for your work on it up till this point.
